# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

# 文件上传接口

POST {{host}}/file/upload
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="2.png"

< C:\Users\ispon\Desktop\2.png
--WebAppBoundary

###

# 文件上传接口

POST {{host}}/file/test
Content-Type: application/json


###
GET {{host}}/hello/test
token: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJKb2UifQ.JKC-Y0bNX7wVFODEdpz-nlP5hNaIyfGWtY53Af7Rb0U

###
###

GET {{host}}/ss
token: eyJoZWFkZXIyIjoiYmJiIiwiaGVhZGVyMSI6ImFhYSIsImFsZyI6IkhTMjU2In0.eyJjMSI6IjExMSIsImMyIjoiMjIyIiwianRpIjoiMGNhZTllOWMtMGExMi00ODYyLThmNzMtYzBiZjJjMTI1YzdkIiwiaXNzIjoiaXN4Y29kZSIsImlhdCI6MTU3Mzk2OTM2Mywic3ViIjoic3ViamVjdCIsImF1ZCI6InlvdSJ9.-PWXYC_y1FzrepBLsFdJgNWaZ7XjmtZlDlmKFAl9oAY


###

POST http://portal.definesys.com:30550/mock/5de1cd117d6f1d000154d3f7/userInfo/getUserInfo?bodyCode=ok
Content-Type: application/json
token: 123456

{
  "userId": "123456"
}

###

POST http://localhost:8888/isxcode/hello/login
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiJ9.eyJjbGFpbSI6ImJsWXJjV05ZWkVsMWJXMU9UVzE0TmtWRVpFVkNOSGwwU2tkWUwyRXdjamRNYldsbllYUldhVFpNVDJWRFZsaFFTMDUyYTJRclMwbHNiMk5SV2tkMEt6RjFMeXRWWVdGaWJVc3pPWFJ0ZG1ndlVqQm9hSEEzVmtkaWNFRlVZWFl4YjBsSkwwaHJOVmQ0THpnMlNUQlBkWGQxWVVONGEySnJRMFIzWm5wbFNGZEhiV2xSY1VoVkwwOVVaM1pWZDBwTE5XbEVXblo1U0hFdk9HeHVaQ3R2UkRkTU9YWkNlRWx0WkROb2J6ZHRiMDVUZG1sbE0yaGlVWGcwWW01b1pVMDAiLCJpYXQiOjE1NzYyMDQ1NDZ9.ViX3r2nz36cAERthkLryGxTAf95W-hFGLRhNCbHgTt0

###

http://localhost:8888/isxcode/hello/test

###